# Use an official PyTorch image with CUDA support as the base image
FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

# Set the working directory in the container
WORKDIR /app

RUN pip install --upgrade pip setuptools

# Install system packages
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY . /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8000"]
